
package GUI;

import DTO.DTO_Phong;
import static GUI.pnl_NhanVien.imageName;
import static GUI.pnl_NhanVien.save_IMG;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ADMIN
 */
public class frm_QLPhong extends javax.swing.JFrame {

    int x, y;
    File f;
    /**
     * Creates new form frm_DSPhong
     */
    public static frm_QLPhong form;

    public frm_QLPhong() {
        initComponents();
        form = this;
//        BLL.BLL_Phong.DoDuLieuBang(tbl_Phong);
        BLL.BLL_Phong.Load_cbbTang(cbb_Tang);
        rab_ChonTang.setSelected(true);
        LuaChon();
    }

    public static boolean save_IMG(File file) {
        File dir = new File("IMG_Phong");
        if (!dir.exists()) {
            dir.mkdirs();
        }

        try {
            File newfile = new File(dir, file.getName());
            Path source = Paths.get(file.getAbsolutePath());
            Path ok = Paths.get(newfile.getAbsolutePath());
            Files.copy(source, ok, StandardCopyOption.REPLACE_EXISTING);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    public void lbl_ImageNV(String ImagePath) {
        ImageIcon icon = new ImageIcon("IMG_Phong\\" + ImagePath);
        Image image = icon.getImage();
        ImageIcon icon1 = new ImageIcon(image.getScaledInstance(lbl_Anh2.getWidth(), lbl_Anh2.getHeight(), image.SCALE_SMOOTH));
        lbl_Anh2.setIcon(icon1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnl_TieuDe = new javax.swing.JPanel();
        lbl_TieuDe = new javax.swing.JLabel();
        btn_Exit = new javax.swing.JButton();
        tab = new javax.swing.JTabbedPane();
        pnl_Phong = new javax.swing.JPanel();
        lbl_MaPhong = new javax.swing.JLabel();
        txt_MaPhong = new javax.swing.JTextField();
        lbl_LoaiPhong = new javax.swing.JLabel();
        cbb_LoaiPhong = new javax.swing.JComboBox<>();
        lbl_DienTich = new javax.swing.JLabel();
        txt_DienTich = new javax.swing.JTextField();
        lbl_m2 = new javax.swing.JLabel();
        lbl_GhiChu = new javax.swing.JLabel();
        pnl_Hinh = new javax.swing.JPanel();
        lbl_Anh2 = new javax.swing.JLabel();
        btn_XoaAnh = new javax.swing.JButton();
        lbl_Hinh = new javax.swing.JLabel();
        pnl_Nut = new javax.swing.JPanel();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Phong = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_GhiChu = new javax.swing.JTextArea();
        btn_LamMoi = new javax.swing.JButton();
        lbl_Tang = new javax.swing.JLabel();
        cbb_Tang = new javax.swing.JComboBox<>();
        txt_NhapTang = new javax.swing.JTextField();
        rab_ChonTang = new javax.swing.JRadioButton();
        rab_NhapTang = new javax.swing.JRadioButton();
        lbl_GiuongDon = new javax.swing.JLabel();
        lbl_GiuongDoi = new javax.swing.JLabel();
        txt_GiuongDon = new javax.swing.JTextField();
        txt_GiuongDOi = new javax.swing.JTextField();
        btn_Tru = new javax.swing.JButton();
        btn_Cong = new javax.swing.JButton();
        btn_Tru2 = new javax.swing.JButton();
        btn_Cong2 = new javax.swing.JButton();
        lbl_Nen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(884, 740));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnl_TieuDe.setBackground(new java.awt.Color(153, 153, 255));
        pnl_TieuDe.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_TieuDeMouseDragged(evt);
            }
        });
        pnl_TieuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_TieuDeMousePressed(evt);
            }
        });

        lbl_TieuDe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TieuDe.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TieuDe.setText("Phòng- Loại phòng");

        btn_Exit.setBackground(new java.awt.Color(255, 0, 0));
        btn_Exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_Exit.setText("X");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_TieuDeLayout = new javax.swing.GroupLayout(pnl_TieuDe);
        pnl_TieuDe.setLayout(pnl_TieuDeLayout);
        pnl_TieuDeLayout.setHorizontalGroup(
            pnl_TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TieuDeLayout.createSequentialGroup()
                .addContainerGap(396, Short.MAX_VALUE)
                .addComponent(lbl_TieuDe)
                .addGap(322, 322, 322)
                .addComponent(btn_Exit))
        );
        pnl_TieuDeLayout.setVerticalGroup(
            pnl_TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TieuDeLayout.createSequentialGroup()
                .addGroup(pnl_TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Exit)
                    .addComponent(lbl_TieuDe))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        tab.setBackground(new java.awt.Color(255, 255, 255));
        tab.setOpaque(true);

        pnl_Phong.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Phong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_Phong.setLayout(null);

        lbl_MaPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaPhong.setText("Mã phòng");
        pnl_Phong.add(lbl_MaPhong);
        lbl_MaPhong.setBounds(48, 14, 61, 17);

        txt_MaPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnl_Phong.add(txt_MaPhong);
        txt_MaPhong.setBounds(174, 14, 203, 23);

        lbl_LoaiPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_LoaiPhong.setText("Loại phòng");
        pnl_Phong.add(lbl_LoaiPhong);
        lbl_LoaiPhong.setBounds(48, 55, 68, 17);

        cbb_LoaiPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnl_Phong.add(cbb_LoaiPhong);
        cbb_LoaiPhong.setBounds(174, 55, 203, 23);

        lbl_DienTich.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_DienTich.setText("Diện tích");
        pnl_Phong.add(lbl_DienTich);
        lbl_DienTich.setBounds(48, 99, 53, 17);

        txt_DienTich.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_DienTich.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_DienTichKeyReleased(evt);
            }
        });
        pnl_Phong.add(txt_DienTich);
        txt_DienTich.setBounds(174, 96, 203, 23);

        lbl_m2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_m2.setText("m2");
        pnl_Phong.add(lbl_m2);
        lbl_m2.setBounds(381, 99, 20, 17);

        lbl_GhiChu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_GhiChu.setText("Ghi chú");
        pnl_Phong.add(lbl_GhiChu);
        lbl_GhiChu.setBounds(233, 333, 46, 17);

        pnl_Hinh.setBackground(new java.awt.Color(255, 255, 255));
      

        lbl_Anh2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_Anh2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Anh2MouseClicked(evt);
            }
        });
       

        btn_XoaAnh.setBackground(new java.awt.Color(255, 0, 0));
        btn_XoaAnh.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btn_XoaAnh.setForeground(new java.awt.Color(255, 255, 255));
        btn_XoaAnh.setText("X");
        btn_XoaAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaAnhActionPerformed(evt);
            }
        });
       

        lbl_Hinh.setText("Hình");
      

        pnl_Phong.add(pnl_Hinh);
        pnl_Hinh.setBounds(13, 339, 168, 224);

        pnl_Nut.setBackground(new java.awt.Color(153, 153, 255));

        btn_Them.setBackground(new java.awt.Color(255, 255, 255));
        btn_Them.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Icon_Cong.png"))); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Icon_Tru.png"))); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(255, 255, 255));
        btn_Sua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon_server.png"))); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_NutLayout = new javax.swing.GroupLayout(pnl_Nut);
        pnl_Nut.setLayout(pnl_NutLayout);
        pnl_NutLayout.setHorizontalGroup(
            pnl_NutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Them)
                .addGap(20, 20, 20)
                .addComponent(btn_Xoa)
                .addGap(18, 18, 18)
                .addComponent(btn_Sua)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_NutLayout.setVerticalGroup(
            pnl_NutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_NutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_NutLayout.createSequentialGroup()
                        .addGroup(pnl_NutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Them)
                            .addComponent(btn_Xoa))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_Phong.add(pnl_Nut);
        pnl_Nut.setBounds(48, 581, 329, 65);

        tbl_Phong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Loại phòng", "Diện tích", "Hình", "Tình trạng", "Tầng"
            }
        ));
        tbl_Phong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_PhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Phong);

        pnl_Phong.add(jScrollPane1);
        jScrollPane1.setBounds(446, 14, 400, 628);

        txt_GhiChu.setColumns(20);
        txt_GhiChu.setRows(5);
        jScrollPane3.setViewportView(txt_GhiChu);

        pnl_Phong.add(jScrollPane3);
        jScrollPane3.setBounds(233, 356, 195, 207);

        btn_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Icon_Reload.png"))); // NOI18N
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });
        pnl_Phong.add(btn_LamMoi);
        btn_LamMoi.setBounds(379, 581, 57, 61);

        lbl_Tang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Tang.setText("Tầng");
        pnl_Phong.add(lbl_Tang);
        lbl_Tang.setBounds(48, 137, 31, 17);

        cbb_Tang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnl_Phong.add(cbb_Tang);
        cbb_Tang.setBounds(174, 137, 203, 23);

        txt_NhapTang.setText("1");
        txt_NhapTang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_NhapTangKeyReleased(evt);
            }
        });
        pnl_Phong.add(txt_NhapTang);
        txt_NhapTang.setBounds(174, 166, 203, 22);

        buttonGroup1.add(rab_ChonTang);
        rab_ChonTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rab_ChonTangActionPerformed(evt);
            }
        });
        pnl_Phong.add(rab_ChonTang);
        rab_ChonTang.setBounds(134, 137, 22, 25);

        buttonGroup1.add(rab_NhapTang);
        rab_NhapTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rab_NhapTangActionPerformed(evt);
            }
        });
        pnl_Phong.add(rab_NhapTang);
        rab_NhapTang.setBounds(134, 165, 22, 25);

        lbl_GiuongDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_GiuongDon.setText("Số giường đơn");
        pnl_Phong.add(lbl_GiuongDon);
        lbl_GiuongDon.setBounds(48, 211, 91, 17);

        lbl_GiuongDoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_GiuongDoi.setText("Số giường đôi");
        pnl_Phong.add(lbl_GiuongDoi);
        lbl_GiuongDoi.setBounds(48, 254, 85, 17);

        txt_GiuongDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_GiuongDon.setText("0");
        txt_GiuongDon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_GiuongDonKeyReleased(evt);
            }
        });
        pnl_Phong.add(txt_GiuongDon);
        txt_GiuongDon.setBounds(174, 208, 111, 23);

        txt_GiuongDOi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_GiuongDOi.setText("0");
        txt_GiuongDOi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_GiuongDOiKeyReleased(evt);
            }
        });
        pnl_Phong.add(txt_GiuongDOi);
        txt_GiuongDOi.setBounds(174, 251, 111, 23);

        btn_Tru.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Tru.setText("-");
        btn_Tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TruActionPerformed(evt);
            }
        });
        pnl_Phong.add(btn_Tru);
        btn_Tru.setBounds(291, 207, 37, 25);

        btn_Cong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Cong.setText("+");
        btn_Cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CongActionPerformed(evt);
            }
        });
        pnl_Phong.add(btn_Cong);
        btn_Cong.setBounds(334, 207, 43, 25);

        btn_Tru2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Tru2.setText("-");
        btn_Tru2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Tru2ActionPerformed(evt);
            }
        });
        pnl_Phong.add(btn_Tru2);
        btn_Tru2.setBounds(291, 250, 37, 25);

        btn_Cong2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Cong2.setText("+");
        btn_Cong2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cong2ActionPerformed(evt);
            }
        });
        pnl_Phong.add(btn_Cong2);
        btn_Cong2.setBounds(334, 250, 43, 25);

        lbl_Nen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/1.jpg"))); // NOI18N
        pnl_Phong.add(lbl_Nen);
        lbl_Nen.setBounds(0, 0, 860, 660);

        tab.addTab("Phòng", pnl_Phong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_TieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static DTO.DTO_Phong P = new DTO_Phong();
    public static String imageName = null;

    private void LuaChon() {//lựa chọn tầng hay tự nhập tầng
        if (rab_ChonTang.isSelected()) {
            txt_NhapTang.setEnabled(false);
            cbb_Tang.setEnabled(true);
        } else {
            cbb_Tang.setEnabled(false);
            txt_NhapTang.setEnabled(true);
        }
    }
    private void btn_XoaAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaAnhActionPerformed
        imageName = null;
        lbl_Anh2.setIcon(null);
    }//GEN-LAST:event_btn_XoaAnhActionPerformed
    private void GanThongTin() {
        P.setMaPhong(txt_MaPhong.getText());
        P.setDienTich(txt_DienTich.getText());
        P.setGhiChu(txt_GhiChu.getText());
        mycombobox mb = (mycombobox) cbb_LoaiPhong.getSelectedItem();
        P.setMaLoaiPhong(mb.value.toString());
        P.setGiuongDon(txt_GiuongDon.getText());
        P.setGiuongDoi(txt_GiuongDOi.getText());
        if (rab_ChonTang.isSelected()) {
            P.setTang(cbb_Tang.getSelectedItem().toString());
            System.out.println("tang " + P.getTang());
        } else {
            P.setTang(txt_NhapTang.getText());
        }
//        System.out.println("loaiphong" + P.getMaLoaiPhong());
        P.setHinh(imageName);
    }

    private void DienTTVaoTextField(String MaPhong) {
        ResultSet rs = DAO.DAO_Phong.LayTheoMa(MaPhong);
        try {
            if (rs.next()) {
                txt_MaPhong.setText(rs.getString("MaPhong"));
                txt_DienTich.setText(String.valueOf(rs.getInt("DienTich")));
                txt_GhiChu.setText(rs.getString("GhiChu"));
                imageName = rs.getString("Hinh");
//                ImageIcon ii = new ImageIcon(new ImageIcon(imageName).getImage().getScaledInstance(lbl_Anh2.getWidth(), lbl_Anh2.getHeight(), Image.SCALE_SMOOTH));
//                lbl_Anh2.setIcon(ii);
                lbl_ImageNV(imageName);
                String MaLoaiPhong = rs.getString("MaLoaiPhong");
                DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cbb_LoaiPhong.getModel();
                for (int i = 0; i < cbb_LoaiPhong.getItemCount(); i++) {
                    mycombobox mb = (mycombobox) cbbModel.getElementAt(i);
                    if (MaLoaiPhong.equals(mb.value)) {
                        txt_NhapTang.setEnabled(false);
                        rab_ChonTang.setSelected(true);
                        cbb_Tang.setEnabled(true);
                        cbb_LoaiPhong.setSelectedIndex(i);
                    } else {
                    }
                }
                for (int i = 0; i < cbb_Tang.getItemCount(); i++) {
                    if (rs.getString("MaTang").matches(cbb_Tang.getItemAt(i))) {
                        cbb_Tang.setSelectedIndex(i);
                    } else {

                    }
                }
                txt_GiuongDon.setText(rs.getString("GiuongDon"));
                txt_GiuongDOi.setText(rs.getString("GiuongDoi"));
            }
        } catch (SQLException ex) {
            System.out.println("kaka loi roi");
        }
    }
    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void pnl_TieuDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TieuDeMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnl_TieuDeMousePressed

    private void pnl_TieuDeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TieuDeMouseDragged
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();
        this.setLocation(x1 - x, y1 - y);
    }//GEN-LAST:event_pnl_TieuDeMouseDragged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        BLL.BLL_Phong.DoDuLieuBang(tbl_Phong);
        BLL.BLL_Phong.loadData_LoaiPhong(cbb_LoaiPhong);
        pnl_LoaiPhong pnl = new pnl_LoaiPhong();
        tab.add("Loại phòng", pnl);
        btn_Sua.setEnabled(false);
        btn_Xoa.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        GanThongTin();
        if (BLL.BLL_Phong.Them(P)) {
            DAO.DAO_Phong.ThemPhong(P);
            BLL.BLL_Phong.DoDuLieuBang(tbl_Phong);
            save_IMG(f);
             BLL.BLL_Phong.Load_cbbTang(cbb_Tang);
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void lbl_Anh2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Anh2MouseClicked
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int resuft = file.showOpenDialog(null);
        if (resuft == JFileChooser.APPROVE_OPTION) {
            f = file.getSelectedFile();
            imageName = f.getAbsolutePath();
            ImageIcon ii = new ImageIcon(new ImageIcon(imageName).getImage().getScaledInstance(lbl_Anh2.getWidth(), lbl_Anh2.getHeight(), Image.SCALE_SMOOTH));
            lbl_Anh2.setIcon(ii);
            imageName = f.getName();
        }
    }//GEN-LAST:event_lbl_Anh2MouseClicked

    private void tbl_PhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_PhongMouseClicked
        if (tbl_Phong.getSelectedRowCount() == 1) {
            btn_Sua.setEnabled(true);
            btn_Xoa.setEnabled(true);
            txt_MaPhong.setFocusable(false);
            int vitri = tbl_Phong.getSelectedRow();
            String MaPhong = tbl_Phong.getValueAt(vitri, 0).toString();
            DienTTVaoTextField(MaPhong);

        }
    }//GEN-LAST:event_tbl_PhongMouseClicked

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        int nutbam = JOptionPane.showConfirmDialog(new JFrame(), "bạn chắc chắn xóa?", "xóA", JOptionPane.YES_NO_OPTION);
        if (nutbam == JOptionPane.YES_OPTION) {
            int cacdong[] = tbl_Phong.getSelectedRows();
            for (int i = 0; i < cacdong.length; i++) {
                String MaPhong = tbl_Phong.getValueAt(cacdong[i], 0).toString();
                if (BLL.BLL_Phong.KT_Xoa(MaPhong)) {
                    DAO.DAO_Phong.Xoa(MaPhong);
                    LamMoi();
                }

            }
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        LamMoi();

    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        GanThongTin();
        if (BLL.BLL_Phong.KT_Sua(P)) {
            DAO.DAO_Phong.Sua(P);
            save_IMG(f);
             BLL.BLL_Phong.Load_cbbTang(cbb_Tang);
            LamMoi();
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void txt_DienTichKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DienTichKeyReleased
        try {
            int sl = Integer.parseInt(txt_DienTich.getText());

        } catch (Exception e) {
            txt_DienTich.setText("0");
        }
    }//GEN-LAST:event_txt_DienTichKeyReleased

    private void rab_ChonTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rab_ChonTangActionPerformed
        LuaChon();
    }//GEN-LAST:event_rab_ChonTangActionPerformed

    private void rab_NhapTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rab_NhapTangActionPerformed
        LuaChon();
    }//GEN-LAST:event_rab_NhapTangActionPerformed

    private void txt_NhapTangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NhapTangKeyReleased
        try {
            int sl = Integer.parseInt(txt_NhapTang.getText());

        } catch (Exception e) {
            txt_NhapTang.setText("0");

        }
    }//GEN-LAST:event_txt_NhapTangKeyReleased
    private void SoLuongGiuongDon(int giatri) {
        int sl = Integer.parseInt(txt_GiuongDon.getText());
        sl = sl + (giatri);
        txt_GiuongDon.setText(String.valueOf(sl));
    }

    private void SoLuongGiuongDoi(int giatri) {
        int sl = Integer.parseInt(txt_GiuongDOi.getText());
        sl = sl + (giatri);
        txt_GiuongDOi.setText(String.valueOf(sl));
    }
    private void txt_GiuongDonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_GiuongDonKeyReleased
        try {
            int sl = Integer.parseInt(txt_GiuongDon.getText());

        } catch (Exception e) {
            txt_GiuongDon.setText("0");

        }
    }//GEN-LAST:event_txt_GiuongDonKeyReleased

    private void btn_TruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TruActionPerformed
        if (!txt_GiuongDon.getText().equals("0")) {
            SoLuongGiuongDon(-1);

        }
    }//GEN-LAST:event_btn_TruActionPerformed

    private void btn_CongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CongActionPerformed
        SoLuongGiuongDon(1);
    }//GEN-LAST:event_btn_CongActionPerformed

    private void txt_GiuongDOiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_GiuongDOiKeyReleased
        try {
            int sl = Integer.parseInt(txt_GiuongDOi.getText());

        } catch (Exception e) {
            txt_GiuongDOi.setText("0");

        }
    }//GEN-LAST:event_txt_GiuongDOiKeyReleased

    private void btn_Tru2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Tru2ActionPerformed
        if (!txt_GiuongDOi.getText().equals("0")) {
            SoLuongGiuongDoi(-1);

        }
    }//GEN-LAST:event_btn_Tru2ActionPerformed

    private void btn_Cong2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cong2ActionPerformed
        SoLuongGiuongDoi(1);
    }//GEN-LAST:event_btn_Cong2ActionPerformed
    private void LamMoi() {
        BLL.BLL_Phong.DoDuLieuBang(tbl_Phong);
        BLL.BLL_Phong.loadData_LoaiPhong(cbb_LoaiPhong);
        txt_MaPhong.setText("");
        txt_DienTich.setText("");
        txt_GhiChu.setText("");
        txt_MaPhong.setFocusable(true);
        imageName = null;
        lbl_Anh2.setIcon(null);
        btn_Sua.setEnabled(false);
        btn_Xoa.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_QLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_QLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_QLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_QLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_QLPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cong;
    private javax.swing.JButton btn_Cong2;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Tru;
    private javax.swing.JButton btn_Tru2;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_XoaAnh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbb_LoaiPhong;
    private javax.swing.JComboBox<String> cbb_Tang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_Anh2;
    private javax.swing.JLabel lbl_DienTich;
    private javax.swing.JLabel lbl_GhiChu;
    private javax.swing.JLabel lbl_GiuongDoi;
    private javax.swing.JLabel lbl_GiuongDon;
    private javax.swing.JLabel lbl_Hinh;
    private javax.swing.JLabel lbl_LoaiPhong;
    private javax.swing.JLabel lbl_MaPhong;
    private javax.swing.JLabel lbl_Nen;
    private javax.swing.JLabel lbl_Tang;
    private javax.swing.JLabel lbl_TieuDe;
    private javax.swing.JLabel lbl_m2;
    private javax.swing.JPanel pnl_Hinh;
    private javax.swing.JPanel pnl_Nut;
    private javax.swing.JPanel pnl_Phong;
    private javax.swing.JPanel pnl_TieuDe;
    private javax.swing.JRadioButton rab_ChonTang;
    private javax.swing.JRadioButton rab_NhapTang;
    public javax.swing.JTabbedPane tab;
    private javax.swing.JTable tbl_Phong;
    private javax.swing.JTextField txt_DienTich;
    private javax.swing.JTextArea txt_GhiChu;
    private javax.swing.JTextField txt_GiuongDOi;
    private javax.swing.JTextField txt_GiuongDon;
    private javax.swing.JTextField txt_MaPhong;
    private javax.swing.JTextField txt_NhapTang;
    // End of variables declaration//GEN-END:variables
}
